### ISSUE TITLE
if you want any function let me know

### ISSUE THREAD

**Issue by theputtipong** [theputtipong/pseudo_data_gen#1]

**Comment by theprachyar** [comment]
gen data from register with simple 
name , email , dob , phone , address , gender

**Comment by theprachyar** [comment]
> gen data from register with simple
> name , email , dob , phone , address , gender

gen data from register with simple
name , email , dob , phone , address , gender

**Comment by theputtipong** [comment]
> > gen data from register with simple
> > name , email , dob , phone , address , gender
> 
> gen data from register with simple name , email , dob , phone , address , gender

ok on progress

**Comment by theprachyar** [comment]
> > > gen data from register with simple
> > > name , email , dob , phone , address , gender
> > 
> > 
> > gen data from register with simple name , email , dob , phone , address , gender
> 
> ok on progress

cool
